# Generated by Django 6.0.4 on 2026-06-16 12:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d+$')])),
                ('telegram_username', models.CharField(blank=True, max_length=256, null=True)),
                ('full_name', models.CharField(max_length=256)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users_user',
                'indexes': [models.Index(fields=['telegram_id'], name='users_user_telegra_b51e4c_idx'), models.Index(fields=['is_blocked'], name='users_user_is_bloc_7849bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('device_id', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.user')),
            ],
            options={
                'db_table': 'users_userdevice',
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_userd_user_id_a5f926_idx')],
            },
        ),
    ]
