# Generated by Django 6.0.4 on 2026-07-30 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("first_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(max_length=256)),
                ("middle_name", models.CharField(max_length=256)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("job", models.CharField(max_length=255)),
                ("about", models.TextField()),
                ("direction", models.CharField(blank=True, max_length=255)),
                ("experience", models.CharField(blank=True, max_length=255)),
                ("work_place", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(upload_to="teachers/images/")),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teachers",
                        to="courses.Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "ordering": ["first_name", "last_name"],
            },
        ),
    ]
