# Generated by Django 6.0.4 on 2026-09-25 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('login', 'Kirish'), ('course_view', "Kursni ko'rish"), ('lesson_view', "Darsni ko'rish"), ('lesson_complete', 'Darsni yakunlash'), ('course_purchase', 'Kurs/obuna sotib olish'), ('task_submit', 'Kod topshiriq yuborish'), ('test_submit', 'Test topshirish'), ('article_view', "Maqolani ko'rish"), ('profile_update', 'Profilni yangilash'), ('other', 'Boshqa')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.user')),
            ],
            options={
                'db_table': 'analytics_user_activity',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='analytics_u_user_id_158bd8_idx'), models.Index(fields=['action', 'created_at'], name='analytics_u_action_a2509b_idx')],
            },
        ),
    ]
