# Generated by Django 6.0.4 on 2026-09-27 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_useractivity'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageExit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('page', models.CharField(max_length=100)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('exit_reason', models.CharField(choices=[('navigation', 'Ichki navigatsiya'), ('tab_close', 'Tab yopildi'), ('browser_close', 'Brauzer yopildi'), ('logout', 'Tizimdan chiqish'), ('idle', 'Faolsizlik'), ('unknown', "Noma'lum")], default='unknown', max_length=20)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Sekundlarda')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'analytics_page_exit',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='useractivity',
            name='anonymous_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='page',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Kirish'), ('page_view', "Sahifani ko'rish"), ('course_view', "Kursni ko'rish"), ('lesson_view', "Darsni ko'rish"), ('lesson_complete', 'Darsni yakunlash'), ('course_purchase', 'Kurs/obuna sotib olish'), ('task_submit', 'Kod topshiriq yuborish'), ('test_submit', 'Test topshirish'), ('article_view', "Maqolani ko'rish"), ('profile_update', 'Profilni yangilash'), ('other', 'Boshqa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['anonymous_id', 'created_at'], name='analytics_u_anonymo_d0cbbc_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['page', 'created_at'], name='analytics_u_page_b22470_idx'),
        ),
        migrations.AddConstraint(
            model_name='useractivity',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('anonymous_id', ''), _negated=True), _connector='OR'), name='useractivity_user_or_anonymous_id'),
        ),
        migrations.AddField(
            model_name='pageexit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_exits', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='pageexit',
            index=models.Index(fields=['page', 'created_at'], name='analytics_p_page_3721c4_idx'),
        ),
        migrations.AddIndex(
            model_name='pageexit',
            index=models.Index(fields=['user', 'created_at'], name='analytics_p_user_id_ec7121_idx'),
        ),
        migrations.AddIndex(
            model_name='pageexit',
            index=models.Index(fields=['anonymous_id', 'created_at'], name='analytics_p_anonymo_360347_idx'),
        ),
        migrations.AddConstraint(
            model_name='pageexit',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('anonymous_id', ''), _negated=True), _connector='OR'), name='pageexit_user_or_anonymous_id'),
        ),
    ]
