# Generated by Django 6.0.4 on 2026-07-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('payme', 'Payme')], default='payme', max_length=20)),
                ('payme_transaction_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('amount_tiyin', models.PositiveBigIntegerField()),
                ('state', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Done'), (-1, 'Canceled')], db_index=True, default=1)),
                ('create_time', models.BigIntegerField(default=0)),
                ('perform_time', models.BigIntegerField(blank=True, null=True)),
                ('cancel_time', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payme_transactions', to='users.user')),
            ],
            options={
                'db_table': 'backend_payme_transaction',
                'ordering': ('-created_at',),
            },
        ),
    ]
